[tool.poetry]
name = "xpinn for pbe"
version = "1.0.0"
description = "Phyisics Informed Neural Network code for Poisson-Boltzmann equation"
authors = ["martinachondo <martin.achondom@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
numpy = "1.24.3"
tensorflow = "2.10.0"
tensorflow-io-gcs-filesystem = "0.31.0"
trimesh = "3.23.5"
scipy = "1.10.1"
matplotlib = "3.6.1"
plotly = "5.14.1"
pandas = "2.0.2"
tqdm = "4.64.1"
rtree = "1.0.1"
ipykernel = "6.16.0"
pydot = "^1.4.2"
pydotplus = "^2.0.2"
numba = "0.57.0"
meshio = "5.3.4"
gmsh = "4.11.1"
bempp-cl = "0.3.0"
xlsxwriter = "^3.1.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
